version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: soundcloud-downloader
    versions:
    - ">= 1.a, < 2"
  - dependency-name: discord.js
    versions:
    - 12.5.2
    - 12.5.3
  - dependency-name: ffmpeg-static
    versions:
    - 4.2.8
    - 4.3.0
  - dependency-name: ytdl-core-discord
    versions:
    - 1.3.0
  - dependency-name: "@discordjs/opus"
    versions:
    - 0.4.0
    - 0.5.0
  - dependency-name: ytdl-core
    versions:
    - 4.5.0
