# These are supported funding model platforms

github: [JaimeTR, WebstrServices]
patreon: JaimeTR
tidelift: npm/JaimeTR-package
custom: ["https://paypal.me/jaimetarazona", https://www.webstrservices.com]

